version: '2'

services:
     portainer_agent:
          image: portainer/agent:2.0.0
          container_name: agent
          ports:
             - 9001:9001
          volumes:
             - /var/run/docker.sock:/var/run/docker.sock
             - /var/lib/docker/volumes:/var/lib/docker/volumes
          restart: always
